=== emg/ricker-berry-synonyms/XML/berry.dtd
<!-- The lexicon element is the highest level element -->
<!ELEMENT lexicon (#PCDATA|entry)* >

<!-- The entry element defines one section, encompassing a single
discussion of a group of words -->
<!ELEMENT entry (#PCDATA|definedWords|content)* >
<!ATTLIST entry
          number CDATA #REQUIRED
          heading CDATA #REQUIRED
>

<!-- definedWords is am unordered list of definedWord elements with whitespace
between. The whitespace can be ignored.
-->
<!ELEMENT definedWords (#PCDATA|definedWord)* >

<!-- definedWord is single tag which has, for each word being defined
in an entry, the strong's number and the word in beta encoding and in
Unicode Greek.
-->
<!ELEMENT definedWord EMPTY >
<!ATTLIST definedWord
          beta CDATA #REQUIRED
          strongs CDATA #REQUIRED 
	  greek CDATA #REQUIRED
>


<!-- The content element is the element containing the content of each
entry. --> 
<!ELEMENT content (#PCDATA|h1|h2|p)* >

<!-- h1 denotes a heading at level 1. It should be centered, and with
a larger font size than h2, as well as being font weight bold -->

<!ELEMENT h1 (#PCDATA)* >

<!-- h2 denotes a heading at level 2. It should be centered, and with
a larger font size than the default document font size, but smaller
than h1. It should be font weight normal. -->
<!ELEMENT h2 (#PCDATA|g)* >

<!-- The g element is a single-tag element which is used to encode a
single word in Greek script. 

The attribute "beta" is the Greek word in BETA encoding.

The attribute "strongs" is the word's number in the Strong's encoding
system.  It is not prefixed by G, but is simply a sequence of digits
0-9.  If this attribute is missing, it means that there is no
equivalent Strong's number.

The attribute "head" is either true or false.  When true, it
designates that the Greek word should stand out, e.g. in bold or with
a color, because it is a promninent mention of a word being defined in
the current section.

The optional attribute "ref", when true, denotes that the word in
question does not belong in this section, but can be found in another
section of the synonyms dictionary.  When the value is "external", the
word in question is not found in the dictionary.

The optional attribute "entry" is only present if and only if
ref==true. In that case, "entry" is the number of the entry in which
the word belongs.

-->
<!ELEMENT g EMPTY >
<!ATTLIST g
          beta   CDATA #REQUIRED 
          strongs  CDATA #IMPLIED
          greek   CDATA #REQUIRED 
          head   (true|false) #REQUIRED 
          ref   (true|external) #IMPLIED 
          entry   CDATA #IMPLIED 
>


<!-- The p element denotes a paragraph. Each paragraph should have its
first line indented by about a half inch.
 -->
<!ELEMENT p (#PCDATA|em|g|scripRef)* >

<!-- The em element designates that the contents should be in italics. -->
<!ELEMENT em
	  (#PCDATA)* >

<!-- The scripRef element designates that the contents is a Scripture
reference.  The reference has been decoded into an OSIS reference
(either a single verse or a range of verses).  See the OSIS standard
definition for how this is encoded.  It is suggested that the href
attribute be used to put a link in the text to the Scripture
referenced.  -->
<!ELEMENT scripRef (#PCDATA)* >
<!ATTLIST scripRef
          href CDATA #REQUIRED
>

=== emg/ricker-berry-synonyms/XML/berry_synonyms.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE lexicon SYSTEM "berry.dtd">
<lexicon>

<entry number="1" heading="Holy, sacred, pure.">
<definedWords>
<definedWord beta="I(ERO/S" strongs="2413" greek="ἱερός" />
<definedWord beta="O(/SIOS" strongs="3741" greek="ὅσιος" />
<definedWord beta="A(/GIOS" strongs="40" greek="ἅγιος" />
<definedWord beta="A(GNO/S" strongs="53" greek="ἁγνός" />
<definedWord beta="SEMNO/S" strongs="4586" greek="σεμνός" /></definedWords>
<content>
<h1>§ 1. Holy, sacred, pure.</h1>

<h2><g beta="I(ERO/S" strongs="2413" greek="ἱερός" head="false"/>, <g beta="O(/SIOS" strongs="3741" greek="ὅσιος" head="false"/>, <g beta="A(/GIOS" strongs="40" greek="ἅγιος"
head="false"/>, <g beta="A(GNO/S" strongs="53" greek="ἁγνός" head="false"/>, <g beta="SEMNO/S" strongs="4586" greek="σεμνός" head="false"/>.</h2>

<p>None of these words in classical Greek has necessarily any moral
significance. Those which now have such a meaning have developed it in
Biblical Greek. <g beta="I(ERO/S" strongs="2413" greek="ἱερός" head="true"/> means
<em>sacred</em>, implying some special relation to God, so that it may
not be violated. It refers, however, to formal relation rather than to
character. It designates an external relation, which ordinarily is not
an internal relation as well. It is used to describe persons or
things. This is the commonest word for <em>holy</em> in classical
Greek, and expresses their usual conception of holiness, but it is
rare in the N.T. because it fails to express the fullness of the
N.T. conception. <g beta="O(/SIOS" strongs="3741" greek="ὅσιος" head="true"/> used of
persons or things, describes that which is in harmony with the divine
constitution of the moral universe. Hence, it is that which is in
accordance with the general and instinctively felt idea of right,
“what is consecrated and sanctioned by universal law and consent”
(Passow), rather than what is in accordance with any system of
revealed truth. As contrary to <g beta="O(/SIOS" strongs="3741" greek="ὅσιος"
head="false"/>, <em>i.e</em>, as <g beta="A)NO/SIOS" strongs="462" greek="ἀνόσιος"
head="false"/>, the Greeks regarded, <em>e.g.</em>, a marriage between
brother and sister such as was common in Egypt, or the omission of the
rites of sepulture in connection with a relative. <g beta="A(/GIOS" strongs="40" greek="ἅγιος" head="true"/> has probably as its fundamental meaning
<em>separation</em>, <em>i.e.</em>, from the world to God's
service. If not the original meaning, this at any rate is a meaning
early in use. This separation, however, is not chiefly external, it is
rather a separation from evil and defilement. The moral signification
of the word is therefore the prominent one. This word, rare and of
neutral meaning in classical Greek, has been developed in meaning, so
that it expresses the full N.T. conception of holiness as no other
does.  <g beta="A(GNO/S" strongs="53" greek="ἁγνός" head="true"/> is probably
related to <g beta="A(/GIOS" strongs="40" greek="ἅγιος" head="false"/>. It means
specifically <em>pure</em>. But this may be only in a ceremonial
sense, or it may have a moral signification. It sometimes describes
freedom from impurities of the flesh. <g beta="SEMNO/S" strongs="4586" greek="σεμνός"
head="true"/> is that which inspires <em>reverence</em> or
<em>awe</em>. In classical Greek it was often applied to the gods. But
frequently it has the lower idea of that which is humanly venerable,
or even refers simply to externals, as to that which is magnificent,
grand, or impressive.</p>


</content>
</entry>

<entry number="2" heading="Sin.">
<definedWords>
</definedWords>
<content>
<h1>§ 2. Sin.</h1>

<h2><g beta="A(MARTI/A" strongs="266" greek="ἁμαρτία" head="false"/>, <g beta="A(MA/RTHMA" strongs="265" greek="ἁμάρτημα" head="false"/>, <g beta="A)SE/BEIA" strongs="763" greek="ἀσέβεια" head="false"/>, <g beta="PARAKOH/" strongs="3876" greek="παρακοή"
head="false"/>, <g beta="A)NOMI/A" strongs="458" greek="ἀνομία" head="false"/>, <g beta="PARANOMI/A" strongs="3892" greek="παρανομία" head="false"/>, <g beta="PARA/BASIS" strongs="3847" greek="παράβασις" head="false"/>, <g beta="PARA/PTWMA" strongs="3900" greek="παράπτωμα"
head="false"/>, <g beta="A)GNO/HMA" strongs="51" greek="ἀγνόημα" head="false"/>, <g beta="H(/TTHMA" strongs="2275" greek="ἥττημα" head="false"/></h2>

<p><g beta="A(MARTI/A" strongs="266" greek="ἁμαρτία" head="true"/>. meant originally
<em>the missing of a mark</em>. When applied to moral things the idea
is similar, it is missing the true end of life, and so it is used as a
general term for sin. It means both the act of sinning and the result,
the sin itself. <g beta="A(MA/RTHMA" strongs="265" greek="ἁμάρτημα" head="true"/> means
only the sin itself, not the act, in its particular manifestations as
separate deeds of disobedience to a divine law.  <g beta="A)SE/BEIA" strongs="763" greek="ἀσέβεια" head="true"/> is <em>ungodliness</em>, positive and
active irreligion, a condition of direct opposition to God. <g beta="PARAKOH/" strongs="3876" greek="παρακοή" head="true"/> is strictly <em>failing to
hear</em>, or hearing carelessly and inattentively. The sin is in this
failure to hear when God speaks, and also in the active disobedience
which ordinarily follows. <g beta="A)NOMI/A" strongs="458" greek="ἀνομία"
head="true"/> is <em>lawlessness</em>, contempt of law, a condition or
action not simply without law, as the etymology might indicate, but
contrary to law. The law is usually by implication the Mosaic law. <g beta="PARANOMI/A" strongs="3892" greek="παρανομία" head="true"/>. occurs only once,
<scripRef href="2Pet.2.16">2 Pet. ii. 16</scripRef>, and is
practically equivalent to <g beta="A)NOMI/A" strongs="458" greek="ἀνομία"
head="false"/>. <g beta="PARA/BASIS" strongs="3847" greek="παράβασις" head="true"/> is
<em>transgression</em>, the passing beyond some assigned limit. It is
the breaking of a distinctly recognized commandment. It consequently
means more than <g beta="A(MARTI/A" strongs="266" greek="ἁμαρτία" head="false"/>. <g beta="PARA/PTWMA" strongs="3900" greek="παράπτωμα" head="true"/> is used in different
senses, sometimes in a milder sense, denoting an error, a mistake, a
fault; and sometimes meaning a trespass, a willful sin. <g beta="A)GNO/HMA" strongs="51" greek="ἀγνόημα" head="true"/> occurs only once,
<scripRef href="Heb.9.7">Heb. ix. 7</scripRef>. It indicates
<em>error</em>, sin which to a certain extent is the result of
ignorance. <g beta="H(/TTHMA" strongs="2275" greek="ἥττημα" head="false"/> denotes
<em>being worsted, defeated</em>.  In an ethical sense it means <em>a
failure in duty, a fault</em>. — All these different words may
occasionally but not usually be used simply to describe the same act
from different points of view. The fundamental meanings of these words
may well be summed up in the language of Trench: Sin “may be regarded
as the missing of a mark or aim: it is then <g beta="A(MARTI/A" strongs="266" greek="ἁμαρτία" head="false"/> or <g beta="A(MA/RTHMA" strongs="265" greek="ἁμάρτημα"
head="false"/>; the overpassing or transgression; of a line: it is
then <g beta="PARA/BASIS" strongs="3847" greek="παράβασις" head="false"/>; the
disobedience to a voice: in which case it is <g beta="PARAKOH/" strongs="3876" greek="παρακοή" head="false"/>; the falling where one should have stood
upright: this will be <g beta="PARA/PTWMA" strongs="3900" greek="παράπτωμα"
head="false"/>; ignorance of what one ought to have known: this will
be <g beta="A)GNO/HMA" strongs="51" greek="ἀγνόημα" head="false"/>; diminishing of
that which should have been rendered in full measure, which is <g beta="H(/TTHMA" strongs="2275" greek="ἥττημα" head="false"/>; non-observance of a law,
which is <g beta="A)NOMI/A" strongs="458" greek="ἀνομία" head="false"/> or <g beta="PARANOMI/A" strongs="3892" greek="παρανομία" head="false"/>.”</p>


</content>
</entry>

<entry number="3" heading="Sincere.">
<definedWords>
</definedWords>
<content>
<h1>§ 3. Sincere.</h1>

<h2><g beta="A(PLOU=S" strongs="573" greek="ἁπλοῦς" head="false"/>, <g beta="A)KE/RAIOS" strongs="185" greek="ἀκέραιος" head="false"/>, <g beta="A)/KAKOS" strongs="172" greek="ἄκακος" head="false"/>, <g beta="A)/DOLOS" strongs="97" greek="ἄδολος"
head="false"/></h2>

<p><g beta="A(PLOU=S" strongs="573" greek="ἁπλοῦς" head="true"/> is literally
<em>spread out without folds</em>, and hence means single, simple,
without complexity of character and motive. In the N.T. this idea of
simplicity is always favorable; in classical Greek the word is also
occasionally used in an unfavorable sense, denoting foolish
simplicity. <g beta="A)KE/RAIOS" strongs="185" greek="ἀκέραιος" head="true"/> also
means <em>simple</em>, literally <em>free from any foreign admixture,
unadulterated, free from disturbing elements</em>. <g beta="A)/KAKOS" strongs="172" greek="ἄκακος" head="true"/> in <scripRef
href="Heb.7.26">Heb. vii. 26</scripRef> means one in whom exists
absence of all evil, and so by implication the presence of all
good. It passes also through the merely negative meaning of absence of
evil, found in S., to the unfavorable meaning of simple, easily
deceived, credulous, which is found in <scripRef href="Rom.16.18">Rom
xvi. 18</scripRef>. <g beta="A)/DOLOS" strongs="97" greek="ἄδολος" head="true"/>
occurring only in <scripRef href="1Pet.2.2">1 Pet. ii. 2</scripRef>,
means <em>sincere</em>, <em>unmixed</em>, <em>without guile</em>.</p>


</content>
</entry>

<entry number="4" heading="Sins of the tongue.">
<definedWords>
</definedWords>
<content>
<h1>§ 4. Sins of the tongue.</h1>

<h2><g beta="MWROLOGI/A" strongs="3473" greek="μωρολογία" head="false"/>, <g beta="AI)SXROLOGI/A" strongs="148" greek="αἰσχρολογία" head="false"/>, <g beta="EU)TRAPELI/A" strongs="2160" greek="εὐτραπελία" head="false"/></h2>

<p><g beta="MWROLOGI/A" strongs="3473" greek="μωρολογία" head="true"/>, used only once in
the N.T., is <em>foolish talking</em>, but this in the Biblical sense
